// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeP-KxBaO5RC7gAL1g9hAek1vJvOl00Tg',
    appId: '1:593549890895:web:1c919d76460f54f359a13a',
    messagingSenderId: '593549890895',
    projectId: 'noqueue-d92ce',
    authDomain: 'noqueue-d92ce.firebaseapp.com',
    databaseURL: 'https://noqueue-d92ce-default-rtdb.firebaseio.com',
    storageBucket: 'noqueue-d92ce.firebasestorage.app',
    measurementId: 'G-FTL9WKN2Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-AN7CCFOCoTJiqYm-up9veZuIpP5JbNs',
    appId: '1:593549890895:android:8b5c212046f83a6b59a13a',
    messagingSenderId: '593549890895',
    projectId: 'noqueue-d92ce',
    databaseURL: 'https://noqueue-d92ce-default-rtdb.firebaseio.com',
    storageBucket: 'noqueue-d92ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDetnKuX49N9AT8PnI2gvG4_4MIMjpmjeI',
    appId: '1:593549890895:ios:c430ffdcc333878059a13a',
    messagingSenderId: '593549890895',
    projectId: 'noqueue-d92ce',
    databaseURL: 'https://noqueue-d92ce-default-rtdb.firebaseio.com',
    storageBucket: 'noqueue-d92ce.firebasestorage.app',
    androidClientId: '593549890895-fipc2dp8seigb82pri7v6gch3vqm6oih.apps.googleusercontent.com',
    iosClientId: '593549890895-6g6h83ht0otrbp92vhfd2mmjiot5gmtu.apps.googleusercontent.com',
    iosBundleId: 'com.noqueue.businessApp',
  );
}
